COUNTRY_FLAGS: dict[str, str] = {
    "afghanistan": ":flag_af:",
    "albania": ":flag_al:",
    "algeria": ":flag_dz:",
    "andorra": ":flag_ad:",
    "angola": ":flag_ao:",
    "argentina": ":flag_ar:",
    "armenia": ":flag_am:",
    "australia": ":flag_au:",
    "austria": ":flag_at:",
    "azerbaijan": ":flag_az:",
    "bahamas": ":flag_bs:",
    "bahrain": ":flag_bh:",
    "bangladesh": ":flag_bd:",
    "belarus": ":flag_by:",
    "belgium": ":flag_be:",
    "belize": ":flag_bz:",
    "benin": ":flag_bj:",
    "bhutan": ":flag_bt:",
    "bolivia": ":flag_bo:",
    "bosnia": ":flag_ba:",
    "botswana": ":flag_bw:",
    "brazil": ":flag_br:",
    "brunei": ":flag_bn:",
    "bulgaria": ":flag_bg:",
    "burkina faso": ":flag_bf:",
    "burundi": ":flag_bi:",
    "cambodia": ":flag_kh:",
    "cameroon": ":flag_cm:",
    "canada": ":flag_ca:",
    "cape verde": ":flag_cv:",
    "central africa": ":flag_cf:",
    "chad": ":flag_td:",
    "chile": ":flag_cl:",
    "china": ":flag_cn:",
    "colombia": ":flag_co:",
    "comoros": ":flag_km:",
    "congo": ":flag_cg:",
    "costa rica": ":flag_cr:",
    "croatia": ":flag_hr:",
    "cuba": ":flag_cu:",
    "cyprus": ":flag_cy:",
    "czechia": ":flag_cz:",
    "denmark": ":flag_dk:",
    "djibouti": ":flag_dj:",
    "dominican republic": ":flag_do:",
    "dr congo": ":flag_cd:",
    "east timor": ":flag_tl:",
    "ecuador": ":flag_ec:",
    "egypt": ":flag_eg:",
    "el salvador": ":flag_sv:",
    "equatorial guinea": ":flag_gq:",
    "eritrea": ":flag_er:",
    "estonia": ":flag_ee:",
    "eswatini": ":flag_sz:",
    "ethiopia": ":flag_et:",
    "fiji": ":flag_fj:",
    "finland": ":flag_fi:",
    "france": ":flag_fr:",
    "gabon": ":flag_ga:",
    "gambia": ":flag_gm:",
    "georgia": ":flag_ge:",
    "germany": ":flag_de:",
    "ghana": ":flag_gh:",
    "greece": ":flag_gr:",
    "greenland": ":flag_gl:",
    "guatemala": ":flag_gt:",
    "guinea": ":flag_gn:",
    "guinea-bissau": ":flag_gw:",
    "guyana": ":flag_gy:",
    "haiti": ":flag_ht:",
    "honduras": ":flag_hn:",
    "hungary": ":flag_hu:",
    "iceland": ":flag_is:",
    "india": ":flag_in:",
    "indonesia": ":flag_id:",
    "iran": ":flag_ir:",
    "iraq": ":flag_iq:",
    "ireland": ":flag_ie:",
    "israel": ":flag_il:",
    "italy": ":flag_it:",
    "ivory coast": ":flag_ci:",
    "jamaica": ":flag_jm:",
    "japan": ":flag_jp:",
    "jordan": ":flag_jo:",
    "kazakhstan": ":flag_kz:",
    "kenya": ":flag_ke:",
    "kosovo": ":flag_xk:",
    "kuwait": ":flag_kw:",
    "kyrgyzstan": ":flag_kg:",
    "laos": ":flag_la:",
    "latvia": ":flag_lv:",
    "lebanon": ":flag_lb:",
    "lesotho": ":flag_ls:",
    "liberia": ":flag_lr:",
    "libya": ":flag_ly:",
    "liechtenstein": ":flag_li:",
    "lithuania": ":flag_lt:",
    "luxembourg": ":flag_lu:",
    "madagascar": ":flag_mg:",
    "malawi": ":flag_mw:",
    "malaysia": ":flag_my:",
    "mali": ":flag_ml:",
    "malta": ":flag_mt:",
    "mauritania": ":flag_mr:",
    "mauritius": ":flag_mu:",
    "mexico": ":flag_mx:",
    "moldova": ":flag_md:",
    "mongolia": ":flag_mn:",
    "montenegro": ":flag_me:",
    "morocco": ":flag_ma:",
    "mozambique": ":flag_mz:",
    "myanmar": ":flag_mm:",
    "namibia": ":flag_na:",
    "nepal": ":flag_np:",
    "netherlands": ":flag_nl:",
    "new zealand": ":flag_nz:",
    "nicaragua": ":flag_ni:",
    "niger": ":flag_ne:",
    "nigeria": ":flag_ng:",
    "north macedonia": ":flag_mk:",
    "norway": ":flag_no:",
    "oman": ":flag_om:",
    "pakistan": ":flag_pk:",
    "palestine": ":flag_ps:",
    "panama": ":flag_pa:",
    "papua new guinea": ":flag_pg:",
    "paraguay": ":flag_py:",
    "peru": ":flag_pe:",
    "philippines": ":flag_ph:",
    "poland": ":flag_pl:",
    "portugal": ":flag_pt:",
    "puerto rico": ":flag_pr:",
    "qatar": ":flag_qa:",
    "romania": ":flag_ro:",
    "russia": ":flag_ru:",
    "rwanda": ":flag_rw:",
    "saudi arabia": ":flag_sa:",
    "senegal": ":flag_sn:",
    "serbia": ":flag_rs:",
    "sierra leone": ":flag_sl:",
    "singapore": ":flag_sg:",
    "slovakia": ":flag_sk:",
    "slovenia": ":flag_si:",
    "solomon islands": ":flag_sb:",
    "somalia": ":flag_so:",
    "south africa": ":flag_za:",
    "south korea": ":flag_kr:",
    "south sudan": ":flag_ss:",
    "spain": ":flag_es:",
    "sri lanka": ":flag_lk:",
    "sudan": ":flag_sd:",
    "suriname": ":flag_sr:",
    "sweden": ":flag_se:",
    "switzerland": ":flag_ch:",
    "syria": ":flag_sy:",
    "são tomé and príncipe": ":flag_st:",
    "taiwan": ":flag_tw:",
    "tajikistan": ":flag_tj:",
    "tanzania": ":flag_tz:",
    "thailand": ":flag_th:",
    "togo": ":flag_tg:",
    "trinidad and tobago": ":flag_tt:",
    "tunisia": ":flag_tn:",
    "turkey": ":flag_tr:",
    "turkiye": ":flag_tr:",
    "turkmenistan": ":flag_tm:",
    "uganda": ":flag_ug:",
    "ukraine": ":flag_ua:",
    "united arab emirates": ":flag_ae:",
    "united kingdom": ":flag_gb:",
    "united korea": ":flag_kr:",
    "united states": ":flag_us:",
    "uruguay": ":flag_uy:",
    "uzbekistan": ":flag_uz:",
    "vanuatu": ":flag_vu:",
    "vatican": ":flag_va:",
    "venezuela": ":flag_ve:",
    "vietnam": ":flag_vn:",
    "yemen": ":flag_ye:",
    "zambia": ":flag_zm:",
    "zimbabwe": ":flag_zw:",
}


def country_flag(country_name: str | None) -> str | None:
    if not country_name:
        return None
    return COUNTRY_FLAGS.get(str(country_name).strip().casefold())


def country_with_flag(country_name: str | None, left: bool) -> str:
    name = str(country_name or "unknown")
    flag = country_flag(name)
    if not flag:
        return name
    if left:
        return f"{flag} {name}"
    else:
        return f"{name} {flag}"
